# Generated by Django 3.1.5 on 2021-02-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=999)),
                ('full_name', models.CharField(max_length=999)),
                ('industry', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialIndicator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(max_length=999)),
                ('indicator_type', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value_name', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialIndicatorMeasure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('indicator_value', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skniprojectmain.company')),
                ('id_indicators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skniprojectmain.financialindicator')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.TimeField()),
                ('value', models.FloatField()),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skniprojectmain.company')),
                ('id_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skniprojectmain.measure')),
            ],
        ),
    ]
