# Generated by Django 3.1.5 on 2021-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skniprojectmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymeasure',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
